services:
  backend:
    build: ./backend
    container_name: feedback-backend
    restart: unless-stopped
    ports:
      - "4000:4000"

  frontend:
    build: ./frontend
    container_name: feedback-frontend
    restart: unless-stopped
    ports:
      - "8085:80"
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=/api

